services:
  mysql:
    # command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    build: ./mysql/
    ports: 
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=admin --password=admin --execute \"use diplomskanaloga; SELECT 1 FROM diplomskanaloga.diplomskadela;\""
      interval: 2s
      timeout: 45s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: diplomskanaloga
    cap_add:
      - SYS_NICE 
  wildfly:
    build: ./wildfly/
    ports: 
      - 8080:8080
      - 8443:8443
      - 9990:9990
    depends_on:
      mysql:
        condition: service_healthy